name: .NET Core Tests

on:
  workflow_dispatch:
    inputs:
      suite:
        description: 'Choose suite: FeaturesSuite, RegressionSuite'
        required: true
        default: FeaturesSuite

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ciCd: true

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x  # Replace 'x' with the desired version (e.g., 6.0.100)

      - name: Install LivingDoc
        run: |
          dotnet tool install --global SpecFlow.Plus.LivingDoc.CLI

      - name: Dotnet build
        run: dotnet build DemoQA_Project_SpecFlow.sln

      - name: Set executable permission for Selenium Manager
        run: |
          chmod +x $(find . -name selenium-manager -type f)

      - name: Run tests with LivingDoc integration
        run: dotnet test DemoQA_Project_SpecFlow.csproj --filter TestCategory=${{ github.event.inputs.suite }} --logger "trx;LogFileName=testresults.trx" /p:CollectSpecFlowProjectInformation=true /p:GenerateSpecFlowLivingDoc=true /p:LivingDocOutputFormat=html

      - name: Upload LivingDoc as artifact
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: LivingDocResults
          path: DemoQA_Project_SpecFlow/TestResults/LivingDoc.html  # Update with the actual path where LivingDoc generates HTML output
